### ISSUE TITLE
My experience installing and running Aletheia on a Mac, some problems & suggestions

### ISSUE THREAD

**Issue by RaspberryCheesecake** [danielquinn/pyletheia#4]
Hallo! I enjoyed your talk at PyCon UK and subsequently installed & tried out Aletheia. It's a really neat idea and I hope more people start using it. As you're looking for feedback, here is mine! I was using a MacBook Air running MacOS High Sierra 10.13.6 to install the Python version of Aletheia.

### You have a twin
I don't know if you're aware of this, but there is [another repository which has a confusingly similar name](https://github.com/daniellerch/aletheia) (*also* by someone called Daniel!)

This was super confusing for me, especially because it's also related to processing images for hidden info. So if you don't read the docs closely you might not notice. At one point I ended up downloading the test image from his repo instead of yours and thinking I was doing something wrong because it wasn't signed!

It would be nice if the docs on your pyletheia & aletheia repos were a little clearer, to help prevent this confusion.

### file-magic/libmagic sadness - caused module to fail on import
I think this might be a Mac-specific thing. I was able to
`$ pip install aletheia`
just fine, but when I came to try and import it in Python code it failed upon import with a mysterious error:
`AttributeError: dlsym(RTLD_DEFAULT, magic_open): symbol not found`

After some judicious googling I realised that I didn't have `libmagic` installed - I followed the instructions in [this page](https://github.com/GOVCERT-LU/eml_parser/issues/9) to `$ brew install libmagic` and then importing aletheia worked for me. (At first I tried installing `file-magic` but found out that was already installed, so clearly wasn't the problem...)

I wonder if there is a way to fix this so that Mac users don't have so much trouble? Or failing that, a more helpful error message would have been great.

### Finding an image to verify took a while
Now I had aletheia working I wanted to play with it! It took a while for me to find an image that I could actually verify was signed by someone else with aletheia though, as the docs didn't point me to anything obvious. First, I mistakenly downloaded images from [that other repo](https://github.com/daniellerch/aletheia/tree/master/sample_images) which gave me an `UnknownFileType` error. I was a little confused but then realised my mistake and tried again with the `syntax.jpg` image from your [proof-of-concept](https://github.com/danielquinn/aletheia/tree/master/proof-of-concept) folder. But that didn't work either :( I saw the `UnparseableFileError`.

While looking for example signed images to try verifying, I browsed your [personal page on aletheia](https://danielquinn.github.io/aletheia/) and the [read the docs site](https://aletheia-project.readthedocs.io/en/latest/) with no luck. It would be helpful if somewhere obvious on these pages there were some embedded images that had been signed with Aletheia for people to download and try.

Finally, I tried searching for [the demo image you used for the presentation]() - and successfully verified it! (running aletheia's `verify()` function on it gave me your website url, hurrah!)

### Errors are a bit ambiguous
I found the `UnparseableFileError` quite ambiguous. I didn't know whether to interpret it as "OK, this image isn't signed, better try another jpg" or "Oh, all .jpg files are not supported, I need to use a different file format" or "This *particular* jpg file is formatted weirdly (somehow corrupted) so it can't be verified, but .jpgs are fine in general". I assumed (1) but maybe I'm wrong?

I would also prefer if `UnknownFileType` was instead something like `UnsupportedFileType` and it would be even nicer if the error description then told me what file types *are* currently supported by aletheia. I had to go back and double check the table on your blog post to be sure, instead.

### I fail at spelling aletheia
I kept writing down `aletheia` as `alethia`. This tripped me up a couple of times when searching and installing things. I've probably misspelled it somewhere in this doc too! At first I thought I had to `$ pip install pylethia` instead of `$ pip install alethia` before I finally realised I wasn't spelling the name correctly.

If you're still looking for contributors I'd be happy to help out with PRs for some of the improvements I'd like to see in pyletheia, especially making the docs clearer for newbies :)

**Comment by danielquinn** [comment]
Wow, this is incredibly helpful, thank you!  All of these are excellent points and I want to address all of them as they all read like exactly the sort of thing a new user would run into.

The twin thing is annoying, because *aletheia* is a surprisingly common name.  I wrestled with what to call this project for a while, but given what it was doing, and the fact that my wife is Greek, I didn't feel like there was a better name out there.  Besides, the name was free on PyPI ;-)  I think I'll add a **Disambiguation** section to the README.  That'd help, right?

If you knew the pain I've had to deal with regarding libmagic/file-magic on this project, you too would cry in frustration.  Your comment here is exactly the kind of comments I'm looking for because as a Linux user, I just don't see this sort of thing.  I think the best place to fix this will be in the documentation in either setup, troubleshooting, or both.

You know, it never occurred to me to offer up a file to use as a test, but your example makes a lot of sense.  I'll make sure to include something in the documentation, maybe a **Quickstart** section with a sample file?

Regarding the `UnparseableFileError`, is the ambiguity at the Python level or the command line?  I ask, because the command line wrapper [interprets this error with a more user-friendly message](https://github.com/danielquinn/pyletheia/blob/master/aletheia/cli.py#L139-L144), but since you're referencing the exception name directly, I'm thinking you started in running the Python directly -- not something I've really made super user-friendly yet.  Perhaps I should be coding those exceptions to include a more user-friendly message so that it's easier to debug.

The spelling is a rough gig, but I'm not sure how to fix that other than to just have a colophon at the bottom of the README to explain the origin and maybe premptively warn about spelling.  I suppose I could install a symlink from `alethia → aletheia` during installation, but that feels a little irresponsible.  If you have a better idea, I'm all ears.

I'll try to give each of these some attention over the next few days, but if you have ideas you'd like to roll into a PR, I'm happy to accept them!

**Comment by danielquinn** [comment]
Well it took me a while to get around to it, but I *think* I've addressed everything here in v1.0.0:

* I've mentioned the similarly-named project in the README
* The libmagic madness is covered now in the [setup documentation](https://aletheia-project.readthedocs.io/en/latest/setup.html#system-dependencies)
* We now have a sample image referenced in the README as well.

Unfortunately, I can' think of anything to help with the spelling.  That's just how you spell it :-)

Anyway, thanks again for the input.  I'm going to close this now.
